//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BostreamWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int AdminId { get; set; }

        [Required(ErrorMessage = "Field required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Field required")]
        public string Username { get; set; }

        public int PersonId { get; set; }
    
        public virtual Person Person { get; set; }
        public object LoginErrorMessage { get; internal set; }
    }
}
