
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BostreamWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {

        this.Quotations = new HashSet<Quotation>();

    }


    public int CustomerID { get; set; }

    public string CompanyName { get; set; }

    public int Phone { get; set; }

    public string Note { get; set; }

    public Nullable<int> TaskID { get; set; }

    public int PersonID { get; set; }



    public virtual Person Person { get; set; }

    public virtual Task Task { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Quotation> Quotations { get; set; }

}

}
